version: '3'

services:
  redis-1:
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
  redis-2:
    image: redis:7.0.4-alpine
    ports:
      - "6380:6379"
    expose:
      - "6380"
  redis-3:
    image: redis:7.0.4-alpine
    ports:
      - "6381:6379"
    expose:
      - "6381"
